CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(256) NOT NULL
);

ALTER TABLE test_submission 
ADD COLUMN submission_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
